name: Build and deploy Node.js app to Azure Web App - Allvekst

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Clear npm cache
        run: npm cache clean --force

      - name: Checkout code
        uses: actions/checkout@v2

      - name: List directory contents
        run: ls -al

      - name: Install dependencies
        run: npm ci
        working-directory: website
      
      - name: Build project
        run: npm run build --if-present
        working-directory: website
      
      - name: Run tests
        run: npm run test --if-present
        working-directory: website

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: website
          path: ./website/build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
  
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: website
          path: ./website/build

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'Allvekst'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_D2A96987C1A147038BAFBF6921836F2E }}
          package: ./website/build
